version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: api-health-check-postgres
    environment:
      POSTGRES_DB: api_health_check
      POSTGRES_USER: api_health_user
      POSTGRES_PASSWORD: api_health_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
